### ISSUE TITLE
custom-domains: Maybe this is the time to use Cloudflare Pages?

### ISSUE THREAD

**Issue by ajhalili2006** [RecapTime/recaptime.github.io#2]
GitHub Pages don't like orange-clouded custom domains (like our domain for this repo, `recpatime.tk`). We may migrate to Cloudflare Pages soon as we're migrated to Yarn as per #1.

**Comment by AndreiJirohHaliliDev2006** [comment]
While GitLab Pages should be fine, the only thing we need to do if we want to go orange-clouded is create an origin cert within the dashboard + adding intermediate certs for Cloudflare and it should be fine.

But sometimes, $#!t can happen, especially if we fricked up things.

**Comment by ajhalili2006** [comment]
Sadly, Cloudflare is having some hiccups while verifying the existence of `recaptime.tk` domain we're currently using, so in the meanwhile, [we hooked up Vercel months ago](https://recaptime-about.vercel.app/).

Probably we can come back to this issue in the future where we got the `.app` domain for @RecapTime squad.
